version: '2.5.1'
services:
  app:
    image: docker-flask-test
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=loja
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3307:3306"
  
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
    - /var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
